# Generated by Django 3.2.6 on 2021-08-02 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='YOUR NAME', max_length=30)),
                ('username', models.CharField(default='YOUR USERNAME', max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('gender', models.CharField(max_length=1)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.TextField()),
                ('date_of_birth', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='place',
        ),
        migrations.RemoveField(
            model_name='waiter',
            name='restaurant',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.DeleteModel(
            name='Waiter',
        ),
        migrations.AddField(
            model_name='ser',
            name='ser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.users'),
        ),
    ]
