# Generated by Django 3.2.6 on 2021-08-02 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210802_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='YOUR NAME', max_length=30)),
                ('gender', models.CharField(max_length=1)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.TextField()),
                ('date_of_birth', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='ser',
            name='ser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.usersdetails'),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
