# Generated by Django 3.2.6 on 2021-08-02 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210802_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ser',
            name='id',
        ),
        migrations.AlterField(
            model_name='ser',
            name='ser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.usersdetails'),
        ),
    ]
