# Generated by Django 3.2.6 on 2021-08-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210802_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdetails',
            name='email',
            field=models.EmailField(default='YOUR EMAIL ADDRESS', max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='usersdetails',
            name='username',
            field=models.CharField(default='YOUR USERNAME', max_length=10),
        ),
        migrations.AlterField(
            model_name='usersdetails',
            name='address',
            field=models.TextField(default='YOUR ADDRESS'),
        ),
        migrations.AlterField(
            model_name='usersdetails',
            name='date_of_birth',
            field=models.DateTimeField(verbose_name=0),
        ),
        migrations.AlterField(
            model_name='usersdetails',
            name='gender',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='usersdetails',
            name='phone',
            field=models.CharField(default='YOUR NUMBER', max_length=11),
        ),
    ]
