# Generated by Django 3.2.6 on 2021-08-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210802_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdetails',
            name='date_of_birth',
            field=models.DateTimeField(),
        ),
    ]
